---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boc-web-predict
    job: worker
    task: "0"
  name: boc-web-predict-worker-0
  namespace: dcdp
spec:
  selector:
    name: boc-web-predict
    job: worker
    task: "0"
  ports:
  - port: 2222
    targetPort: 2222

---
apiVersion: batch/v1
kind: Job
metadata:
  name: boc-web-predict-worker-0
  namespace: dcdp
spec:
  template:
    metadata:
      labels:
        name: boc-web-predict
        job: worker
        task: "0"
    spec:
      containers:
      - name: boc-web-predict-worker-0
        image: docker.5cu9kz.cloud.boc.com/tensorflow:1.4.0
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
            python /src/boc-web-predict/train.py \
                   --ps_hosts=boc-web-predict-ps-0.dcdp:2222 \
                   --worker_hosts=boc-web-predict-worker-0.dcdp:2222,boc-web-predict-worker-1.dcdp:2222 \
                   --job_name=worker \
                   --task_index=0 \
                   --data_dir=/data/boc-web-predict \
                   --data_name=data.csv \
                   --model_dir=/model/boc-web-predict/checkpoint \
                   --log_path=/log/boc-web-predict \
                   1>>/log/boc-web-predict/boc-web-predict-worker-0.log 2>>/log/boc-web-predict/boc-web-predict-worker-0.errlog ;"]
        volumeMounts: 
        - name: data
          mountPath: /data
        - name: log
          mountPath: /log
        - name: model
          mountPath: /model
        - name: src
          mountPath: /src
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-dcdp-data
        - name: log
          persistentVolumeClaim:
            claimName: pvc-dcdp-log
        - name: src
          persistentVolumeClaim:
            claimName: pvc-dcdp-src
        - name: model
          persistentVolumeClaim:
            claimName: pvc-dcdp-model


---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boc-web-predict
    job: worker
    task: "1"
  name: boc-web-predict-worker-1
  namespace: dcdp
spec:
  selector:
    name: boc-web-predict
    job: worker
    task: "1"
  ports:
  - port: 2222
    targetPort: 2222

---
apiVersion: batch/v1
kind: Job
metadata:
  name: boc-web-predict-worker-1
  namespace: dcdp
spec:
  template:
    metadata:
      labels:
        name: boc-web-predict
        job: worker
        task: "1"
    spec:
      containers:
      - name: boc-web-predict-worker-1
        image: docker.5cu9kz.cloud.boc.com/tensorflow:1.4.0
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
            python /src/boc-web-predict/train.py \
                   --ps_hosts=boc-web-predict-ps-0.dcdp:2222 \
                   --worker_hosts=boc-web-predict-worker-0.dcdp:2222,boc-web-predict-worker-1.dcdp:2222 \
                   --job_name=worker \
                   --task_index=1 \
                   --data_dir=/data/boc-web-predict \
                   --data_name=data.csv \
                   --model_dir=/model/boc-web-predict/checkpoint \
                   --log_path=/log/boc-web-predict \
                   1>>/log/boc-web-predict/boc-web-predict-worker-1.log 2>>/log/boc-web-predict/boc-web-predict-worker-1.errlog ;"]
        volumeMounts: 
        - name: data
          mountPath: /data
        - name: log
          mountPath: /log
        - name: model
          mountPath: /model
        - name: src
          mountPath: /src
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-dcdp-data
        - name: log
          persistentVolumeClaim:
            claimName: pvc-dcdp-log
        - name: src
          persistentVolumeClaim:
            claimName: pvc-dcdp-src
        - name: model
          persistentVolumeClaim:
            claimName: pvc-dcdp-model


---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boc-web-predict
    job: ps
    task: "0"
  name: boc-web-predict-ps-0
  namespace: dcdp
spec:
  selector:
    name: boc-web-predict
    job: ps
    task: "0"
  ports:
  - port: 2222
    targetPort: 2222


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boc-web-predict-ps-0
  namespace: dcdp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: boc-web-predict
        job: ps
        task: "0"
    spec:
      containers:
      - name: boc-web-predict-ps-0
        image: docker.5cu9kz.cloud.boc.com/tensorflow:1.4.0
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
            python /src/boc-web-predict/train.py \
                   --ps_hosts=boc-web-predict-ps-0.dcdp:2222 \
                   --worker_hosts=boc-web-predict-worker-0.dcdp:2222,boc-web-predict-worker-1.dcdp:2222 \
                   --job_name=ps \
                   --log_path=/log/boc-web-predict \
                   1>>/log/boc-web-predict/boc-web-predict-ps-0.log 2>>/log/boc-web-predict/boc-web-predict-ps-0.errlog ;"]
        volumeMounts: 
        - name: data
          mountPath: /data
        - name: log
          mountPath: /log
        - name: model
          mountPath: /model
        - name: src
          mountPath: /src
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-dcdp-data
        - name: log
          persistentVolumeClaim:
            claimName: pvc-dcdp-log
        - name: src
          persistentVolumeClaim:
            claimName: pvc-dcdp-src
        - name: model
          persistentVolumeClaim:
            claimName: pvc-dcdp-model

---

